# Generated by Django 5.2.17 on 2026-09-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userotp',
            name='accounts_us_user_id_ae3018_idx',
        ),
        migrations.AddField(
            model_name='userotp',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('password_reset', 'Password reset')], default='register', max_length=30),
        ),
        migrations.AddIndex(
            model_name='userotp',
            index=models.Index(fields=['user', 'purpose', 'otp_code'], name='accounts_us_user_id_746fbc_idx'),
        ),
    ]
